#!/usr/bin/env bash
# Regenerate mods/homebrew/dx4homelab.Brewfile from THIS workstation's currently
# installed Homebrew packages. Run LOCALLY only (needs brew); it is never invoked
# by CI or the image build — it just refreshes the committed Brewfile.
#
#   ./mods/update-brew-installed-apps-run-localy-only.sh
#   git add mods/homebrew/dx4homelab.Brewfile && git commit
#
set -euo pipefail

# Operate from the repo root no matter where this is invoked from.
cd "$(git -C "$(dirname "$0")" rev-parse --show-toplevel)"
BREWFILE="mods/homebrew/dx4homelab.Brewfile"

# Make sure brew is reachable even in a non-login shell.
if ! command -v brew >/dev/null 2>&1; then
    if [ -x /home/linuxbrew/.linuxbrew/bin/brew ]; then
        eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
    else
        echo "Homebrew not found on this machine." >&2
        exit 1
    fi
fi

# Write a stable header, then the tap/brew/cask lines from `brew bundle dump`.
# (dump also emits vscode/flatpak/mas lines — those are not brew packages.)
{
    echo "# dx4homelab Homebrew packages — manually-installed CLI tools + casks."
    echo "# Regenerated by $(basename "$0"); do not hand-edit the list below."
    echo "# Baked into the dx image at /usr/share/ublue-os/homebrew/dx4homelab.Brewfile;"
    echo "# install on a deployed instance with:  ujust install-dx4homelab-brews"
    echo
    brew bundle dump --file=- | grep -E '^(tap|brew|cask) '
} > "${BREWFILE}"

echo "Wrote $(grep -cE '^(tap|brew|cask) ' "${BREWFILE}") package entries to ${BREWFILE}"
