name: Build dx4homelab/bluefin/dx GTS
on:
  # merge_group:
  # pull_request:
  #   branches:
  #     - main
  #     - testing
  #   paths-ignore:
  #     - '**.md'
  #     - 'system_files/kinoite/**'
  # push:
  #   branches:
  #     - main
  #   paths-ignore:
  #     - '**.md'
  #     - 'system_files/kinoite/**'
  # schedule:
  #   - cron: '0 7 * * *'  # At 07:00 AM UTC everyday => 1AM MST

  workflow_dispatch:

permissions:
  packages: write

jobs:
  build:
    name: build
    uses: ./.github/workflows/reusable-build.yml
    secrets: inherit
    with:
      brand_name: bluefin
      fedora_version: gts
